### ISSUE TITLE
npm/node run doesn't get env set

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord-vscode#26]
When running using npm/node the remote env isn't fetched.

**Comment by aviramha** [comment]
It might be that mirrord doesn't even load into it because they use `dotenv` script that loads it from file on the pod.
It might be that we need to add SIP Patching?

**Comment by t4lz** [comment]
Does this only happen on vscode or also with the CLI?

**Comment by aviramha** [comment]
@t4lz Thanks for posting the project. The dotenv is external (meaning they use the cli to run their code)
Add to your `package.json` a script that does `dotenv -e FILE node index.js` and then in your launch json run that.

**Comment by t4lz** [comment]
> Add to your `package.json` a script that does `dotenv -e FILE node index.js` and then in your launch json run that.

[Did that](https://github.com/t4lz/npm-dotenv/commit/ab95758f3527af2e1d412b754b75d517fb43fb53) and it still doesn't reproduce for me. Trying to think what I could be doing differently.

**Comment by aviramha** [comment]
> > Add to your `package.json` a script that does `dotenv -e FILE node index.js` and then in your launch json run that.
> 
> [Did that](https://github.com/t4lz/npm-dotenv/commit/ab95758f3527af2e1d412b754b75d517fb43fb53) and it still doesn't reproduce for me. Trying to think what I could be doing differently.

There's a specific launch configuration for npm run script. They used it.
You can also do it if you go to `package.json` from the IDE and click debug next to the script you added.

**Comment by aviramha** [comment]
![image](https://github.com/metalbear-co/mirrord-vscode/assets/41201924/48d0c218-58db-4359-8626-158d3afaaf43)

Ignore the scripts, just using this as an example :) (You can see a small debug button then you can choose what script to run)

**Comment by t4lz** [comment]
> ![image](https://user-images.githubusercontent.com/41201924/253239637-48d0c218-58db-4359-8626-158d3afaaf43.png)

When running that way (clicking on the little "Debug" button above `scripts`), a run configuration with request type `attach` is used by vs-code:
![image](https://github.com/metalbear-co/mirrord-vscode/assets/12370607/b6bf9a38-2ea7-486c-9dd7-5878f07d5508)
And [the `env` launch configuration field is only available for launch configurations of request type `launch`](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configuration-attributes).

This of course means the layer is not injected into the process. This is not a SIP issue, it also wouldn't work on Linux.

Trying to think how we could support this way of launching. I don't think simply changing the request type would do, because it seems this configuration does not contain the information of which file to run etc. Also probably it's a different flow for the IDE.

**Comment by t4lz** [comment]
> There's a specific launch configuration for npm run script. They used it.

Am I not using it in the commit I linked above? (not talking about the debug button in `package.json` now, but about vscode's `launch.json`)
I followed vscode's [Launch configuration support for 'npm' and other tools](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configuration-support-for-npm-and-other-tools) documentation.

**Comment by aviramha** [comment]
They had something like this:
```json
    {
      "command": "npm run build:prod",
      "name": "Run npm start",
      "request": "launch",
      "type": "node-terminal"
    },
```
